config/routes.rb
RailsApp::Application.routes.draw do
  resources :users, :user_settings, :sessions, :post_types

  resources :photos do
    resources :photo_copyrights
    member do
      get :copy_temp
      get :copy_protect
    end
  end

  resources :posts do
    resources :photos
    collection do
      get 'select_post_type'
    end
    member do
      get 'publish'
      get 'unpublish'
    end
  end

  root to: "static_pages#home"
  match '/signin', to: "sessions#new"
  match '/signout', to: "sessions#destroy"
  match '/signup', to: "users#new"
  match '/password_reset', to: "users#password_reset"
  match '/settings', to: "user_settings#edit"
  match '/update_copy_notice', to: "photo_copyrights#update_default_copyright"
  match '/backup', to: "Users#backup"
  match '/restore', to: "Users#restore"
  match ':id', to:"posts#index"
end

app/controllers/post_types_controller.rb
class PostTypesController < ApplicationController
  before_filter :signed_in_user
  def new
    @post_type = PostType.new
    @post_types = PostType.all.drop(1)
  end

  def create
    @post_type = PostType.new(params[:post_type])
    if @post_type.save
      redirect_to post_types_path
    else
      @post_types = PostType.all.drop(1)
      render 'new'
    end
  end

  def edit
    @post_type = PostType.find(params[:id])
    @post_types = PostType.all
  end

  def update
    @post_type = PostType.find(params[:id])
    if @post_type.update_attributes(params[:post_type])
      redirect_to post_types_path
    else
      @post_types = PostType.all.drop(1)
      render 'new'
    end
  end
  
  def show
    redirect_to posts_path(post_type:params[:id])
  end

  def index
    @post_types = PostType.where("parent_type_id IS ?", nil).drop(1)
  end

  def destroy
    if params[:id] != 1
      @post_type = PostType.find(params[:id])
      @post_type.destroy
    else
      flash[:error] = "Sorry, but you cannot delete first post type."
    end
    redirect_to post_types_path
  end
end

app/views/post_types/_post_type_form.html.erb
<%= form_for @post_type, :html => {class:"large-7 large-centered columns"} do |f| %>
  <%= f.label :name, class:"required" %>
  <%= f.text_field :name %>

  <% if false %>
    <%= f.label :description %>
    <%= f.text_field :description %>
  <% end %>

  <% if !@post_types.empty? %>
    <%= f.label :parent_type_id, "Parent Type (optional)" %>
    <%= f.collection_select :parent_type_id, @post_types, :id, :name, {:prompt => "None"} %>
  <% end %>

  <div class="row">
    <div class="small-6 columns">
      <%= f.label :shifty_type, class:"check-label" do %>
        <%= f.check_box :shifty_type %>
        Shifty Type
      <% end %>
    </div>
    <div class="small-6 columns">
      <%= f.label :hidden_type, class:"check-label" do %>
        <%= f.check_box :hidden_type %>
        Hidden Type
      <% end %>
    </div>
  </div>

  <%= f.submit (params[:action] == "new")?"Create Post":"Update Post",
    class:"button expand radius"
  %>
<% end %>

app/views/post_types/edit.html.erb
<h1 class="text-center">Edit Post Type</h1>
<%= render "post_type_form" %>

app/views/post_types/index.html.erb
<h1 class="text-center">Post Types</h1>
<div class="columns large-10 large-centered">
  <ul class="pseudo-table no-bullet">
    <li class="pseudo-headers text-center row">
      <div class="columns large-2 hide-for-small">
        Date
      </div>
      <div class="columns small-6">
        Title
      </div>
      <div class="columns large-4 small-6">
        Modify
      </div>
    </li>
    <% @post_types.each do |post_type| %>
      <li class="row">
        <div class="columns large-2 hide-for-small text-center">
          <%= post_type.created_at.strftime("%-m-%-d-%y") %>
        </div>
        <div class="columns small-6">
          <%= link_to post_type.name, "/#{post_type.name}" %>
        </div>
        <div class="text-center">
          <div class="columns large-2 small-3">
            <%= link_to "Edit", edit_post_type_path(post_type) %>
          </div>
          <div class="columns large-2 small-3">
            <%= link_to "Delete", post_type, method: :delete, confirm:"Delete post_type?" %>
          </div>
        </div>
      </li>

      <% children = PostType.where("parent_type_id = ?", post_type.id) %>

      <% if !children.empty? %>
        <% children.each do |child_type| %>
          <li class="row">
            <div class="columns large-2 hide-for-small text-center">
              <%= child_type.created_at.strftime("%-m-%-d-%y") %>
            </div>
            <div class="columns small-6">
              <%= link_to "---- #{child_type.name}", child_type %>
            </div>
            <div class="text-center">
              <div class="columns large-2 small-3">
                <%= link_to "Edit", edit_post_type_path(child_type) %>
              </div>
              <div class="columns large-2 small-3">
                <%= link_to "Delete", child_type, method: :delete, confirm:"Delete child_type?" %>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
  <div class="row">
    <%= link_to '<i class="fi-plus"></i> New Post Type'.html_safe, new_post_type_path, class:"button expand" %>
  </div>
</div>

app/views/post_types/new.html.erb
<h1 class="text-center">New Post Type</h1>
<%= render "post_type_form" %>