config/routes.rb
RailsApp::Application.routes.draw do
  resources :users, :user_settings, :sessions, :post_types

  resources :photos do
    resources :photo_copyrights
    member do
      get :copy_temp
      get :copy_protect
    end
  end

  resources :posts do
    resources :photos
    collection do
      get 'select_post_type'
    end
    member do
      get 'publish'
      get 'unpublish'
    end
  end

  root to: "static_pages#home"
  match '/signin', to: "sessions#new"
  match '/signout', to: "sessions#destroy"
  match '/signup', to: "users#new"
  match '/password_reset', to: "users#password_reset"
  match '/settings', to: "user_settings#edit"
  match '/update_copy_notice', to: "photo_copyrights#update_default_copyright"
  match '/backup', to: "Users#backup"
  match '/restore', to: "Users#restore"
  match ':id', to:"posts#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, 
    :password_confirmation, :remember_token, 
    :flickr_api_key, :flickr_shared_secret, 
    :flickr_access_token, :flickr_access_secret, 
    :flickr_auth_url, :flickr_oauth_token, 
    :flickr_oauth_token_secret

  has_secure_password

  validates_presence_of :email, :name, :flickr_api_key, :flickr_shared_secret

  def validate_flickr_url
    require 'flickraw'

    FlickRaw.api_key= self.flickr_api_key
    FlickRaw.shared_secret= self.flickr_shared_secret

    token = flickr.get_request_token 
    url = flickr.get_authorize_url(
      token['oauth_token'], 
      :perms => 'write'
    ) 

    # Credentials for update_flickr_credentials
    self.flickr_auth_url = url
    self.flickr_oauth_token = token['oauth_token']
    self.flickr_oauth_token_secret = token['oauth_token_secret']
    self.save

    return url
  end

  # if false encrypt access_token and access_secret or find workaround
  def update_flickr_credentials(verify_token)
    require 'flickraw'

    FlickRaw.api_key= self.flickr_api_key
    FlickRaw.shared_secret= self.flickr_shared_secret

    flickr.get_access_token(self.flickr_oauth_token, self.flickr_oauth_token_secret, verify_token.strip)

    if login = flickr.test.login
      self.flickr_user_id = login.id
      self.flickr_access_token = flickr.access_token
      self.flickr_access_secret = flickr.access_secret

      self.flickr_oauth_token = nil
      self.flickr_oauth_token_secret = nil
      self.flickr_auth_url = nil

      self.save
    end
  end

  def backup
    require 'csv'

    CSV.generate do |csv|
      PostType.all.each do |post_type|
        csv << [
          post_type.id,
          post_type.name,
          post_type.description,
          post_type.parent_type_id,
          post_type.shifty_type,
          post_type.hidden_type
        ]
      end

      csv << []

      Post.all.each do |post|
        csv << [
          post.id,
          post.title,
          post.content,
          post.post_type_id,
          post.published_at
        ]
      end

      csv << []

      Photo.all.each do |photo|
        csv << [
          photo.id,
          photo.title,
          photo.description,
          photo.post_id,
          photo.server,
          photo.secret,
          photo.farm,
          photo.flickr_id,
          photo.ow,
          photo.oh,
          photo.image_file_size
        ]
      end

      csv << []

      photo_copyright = PhotoCopyright.first
      csv << [
        photo_copyright.notice,
        photo_copyright.opacity,
        photo_copyright.size,
        photo_copyright.color,
        photo_copyright.top_offset,
        photo_copyright.left_offset
      ]

      csv << []

      user_setting = UserSetting.first
      csv << [
        user_setting.title,
        user_setting.slogan,
        user_setting.copy_notice,
        user_setting.time_zone,
        user_setting.font_link,
        user_setting.font_style
      ]
    end
  end

  def restore_from(backup_file)
    require 'csv'
    model_type = 0

    tables = ["post_types","posts","photos","photo_copyrights"]

    #clear the tables
    tables.each do |table|
      if Rails.env.production?
        ActiveRecord::Base.connection.execute("TRUNCATE #{table}")
      else
        ActiveRecord::Base.connection.execute("DELETE from #{table}")
        ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = '#{table}'")
      end
    end

    CSV.foreach(backup_file.path, headers:false) do |row|
      if row.empty?
        model_type = model_type + 1
      else
        create_with_filler(row,model_type)
      end
    end

    #clean up filler records
    Photo.where("title = ?","blankshifty").destroy_all
    Post.where("title = ?","blankshifty").destroy_all
    PostType.where("name = ?","blankshifty").destroy_all
  end

  private
    def create_with_filler(row, model_type)
      record_id = row[0].to_i

      case model_type
      when 0
        post_type_create(record_id, row)
      when 1
        post_create(record_id, row)
      when 2
        photo_create(record_id, row)
      when 3
        PhotoCopyright.create!(
          notice:row[0],
          opacity:row[1],
          size:row[2],
          color:row[3],
          top_offset:row[4],
          left_offset:row[5]
        )
      when 4
        UserSetting.first.update_attributes(
          title:row[0],
          slogan:row[1],
          copy_notice:row[2],
          time_zone:row[3],
          font_link:row[4],
          font_style:row[5]
        )
      end
    end

    def post_type_create(record_id, row)
      #recursive call to fill in gaps
      if record_id > 1 && PostType.where("id = ?",record_id - 1).empty?
        post_type_create(record_id - 1,[])
      end

      #create record if row present, otherwise make and delete filler record
      if !row.empty?
        PostType.create!(
          name:row[1],
          description:row[2],
          parent_type_id:row[3],
          shifty_type:row[4],
          hidden_type:row[5]
        )
      else
        post_type = PostType.create!(name:"blankshifty")
      end
    end

    def post_create(record_id, row)
      #recursive call to fill in gaps
      if record_id > 1 && Post.where("id = ?",record_id - 1).empty?
        post_create(record_id - 1,[])
      end

      #create record if row present, otherwise make and delete filler record
      if !row.empty?
        Post.create!(
          title:row[1],
          content:row[2],
          post_type_id:row[3],
          published_at:row[4],
          user_id:1
        )
      else
        post = Post.create!(title:"blankshifty")
      end
    end

    def photo_create(record_id, row)
      #recursive call to fill in gaps
      if record_id > 1 && Photo.where("id = ?",record_id - 1).empty?
        photo_create(record_id - 1,[])
      end

      #create record if row present, otherwise make filler record
      if !row.empty?
        Photo.create!(
          title:row[1],
          description:row[2],
          post_id:row[3],
          server:row[4],
          secret:row[5],
          farm:row[6],
          flickr_id:row[7],
          ow:row[8],
          oh:row[9],
          image_file_size:row[10]
        )
      else
        Photo.create!(title:"blankshifty")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def password_reset
    if params[:current_password]
      if current_user.authenticate(params[:current_password])
        current_user.update_attributes(password:params[:password], password_confirmation:params[:password_confirmation])
        if current_user.authenticate(params[:password])
          flash[:success] = "Password Successfully Changed"
          redirect_to edit_user_path(current_user)
        else
          flash[:error] = "The new password was not accepted. The new password must be at least 6 characters long and the password confimation must match."
        end
      else
        flash[:error] = "Invalid current password. Please try again."
      end
    end
  end

  def backup
    file_name = Time.zone.now.strftime("%Y-%m-%d") + "-shiftypages-backup.csv"
    if params[:password]
      if current_user.authenticate(params[:password])
        send_data current_user.backup, :filename => file_name
      else
        flash[:error] = "Incorrect password. Please try again."
      end
    end
  end

  def restore
    if request.put? || request.post?
      if current_user.authenticate(params[:password])
        if params[:backup_file] && params[:backup_file].content_type == "text/csv"
          current_user.restore_from(params[:backup_file])
          redirect_to root_path
        else
          flash[:error] = "Something appears to have gone wrong, please check to make sure that the file is a backup.csv file downloaded from this site."
        end
      else
        flash[:error] = "Incorrect password. Please try again."
      end
    end
  end

  private
    #filters for limiting users to 1 and finalizing settings
    def signed_in
      unless signed_in? || User.first.nil?
        redirect_to root_path
        return
      end
      if signed_in? && settings.nil?
        redirect_to new_user_setting_path
      end
    end
end

app/views/users/_user_form.html.erb
<div class="columns large-7 large-centered">
  <% if params[:action] == "edit" %>
    <div class="text-center bottom-12 small-7 small-centered columns">
      <%= link_to '<i class="fi-key"></i> Change Password'.html_safe, password_reset_path, class:"button expand small radius" %>
    </div>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="no-bullet errors text-center">
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_for @user do |f| %>
    <%= f.label :name, "Your Name", class:"required" %>
    <%= f.text_field :name, :autofocus => true %>

    <%= f.label :email, class:"required" %>
    <%= f.text_field :email %>

    <% if params[:action] == "new" || params[:action] == "create" %>
      <%= f.label :password, class:"top-24 required" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, class:"required" %>
      <%= f.password_field :password_confirmation %>

      <h3 class="text-center top-12">Flickr API</h3>
      <div class="text-center line-15">
        To use Flickr image hosting you must obtain Flickr API access. To apply for a key, click the "Create Key" button. Once you have your key and shared secret, copy and paste them into the fields below.
      </div>

      <div class="columns small-8 small-centered top-24">
        <%= link_to '<i class="fi-key"></i> Create Key'.html_safe, 
          "https://www.flickr.com/services/apps/create/apply/", 
          target:"_blank",
          class:"button expand radius" 
        %>
      </div>

      <%= f.label :flickr_api_key, "API Key", class:"required" %>
      <%= f.text_field :flickr_api_key %>

      <%= f.label :flickr_shared_secret, "Shared Secret", class:"required" %>
      <%= f.text_field :flickr_shared_secret %>
    <% end %>

    <%= f.submit (params[:action]=="new")?"Save & Continue":"Update Account", class:"button expand radius top-24" %>
  <% end %>
</div>

app/views/users/backup.html.erb
<div class="row">
  <div class="large-7 large-centered columns">
    <h1 class="text-center">Backup Site</h1>
    <p class="text-center bottom-18">
      This will create a backup file based on the current records and settings for the site. Please enter your password to continue.
    </p>
    <%= form_tag backup_path do %>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      <%= submit_tag "Backup", class:"button expand radius top-18" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Edit Account</h1>
<%= render 'user_form' %>

app/views/users/new.html.erb
<div class="columns text-center">
	<h1>Welcome to your site!</h1>
	<p>Please create an account to begin.</p>
</div>
<%= render 'user_form' %>

app/views/users/password_reset.html.erb
<div class="row">
  <div class="large-7 large-centered columns">
    <h1 class="text-center">Password Reset</h1>
    <p class="text-center bottom-18">
      Afraid someone might have found out your password?<br> Reset it here.
    </p>
    <%= form_tag password_reset_path do %>
      <%= label_tag :current_password %>
      <%= password_field_tag :current_password %>
      <%= label_tag :password, "New password" %>
      <%= password_field_tag :password %>
      <%= label_tag :password_confirmation %>
      <%= password_field_tag :password_confirmation %>
      <%= submit_tag "Backup", class:"button expand radius top-18" %>
    <% end %>
  </div>
</div>

app/views/users/restore.html.erb
<div class="row">
  <div class="large-7 large-centered columns">
    <h1 class="text-center">Restore Site</h1>
    <p class="text-center bottom-18">
      <b>Warning:</b> This will delete all existing records and will attempt to restore the site from the information on the backup file. Proceed with caution.
    </p>
    <%= form_tag restore_path, multipart: true do %>
      <%= file_field_tag :backup_file %>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      <%= submit_tag "Restore From Backup", class:"button expand radius" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<h1><%= @user.name %></h1>
	<p><%= @user.about_me %></p>
</div>