config/routes.rb
RailsApp::Application.routes.draw do
  resources :users, :user_settings, :sessions, :post_types

  resources :photos do
    resources :photo_copyrights
    member do
      get :copy_temp
      get :copy_protect
    end
  end

  resources :posts do
    resources :photos
    collection do
      get 'select_post_type'
    end
    member do
      get 'publish'
      get 'unpublish'
    end
  end

  root to: "static_pages#home"
  match '/signin', to: "sessions#new"
  match '/signout', to: "sessions#destroy"
  match '/signup', to: "users#new"
  match '/password_reset', to: "users#password_reset"
  match '/settings', to: "user_settings#edit"
  match '/update_copy_notice', to: "photo_copyrights#update_default_copyright"
  match '/backup', to: "Users#backup"
  match '/restore', to: "Users#restore"
  match ':id', to:"posts#index"
end

app/views/layouts/_account_menu.html.erb
<div>
  <%= link_to '<i class="fi-torso"></i> Personal Info'.html_safe, edit_user_path(current_user) %>
</div>
<div>
  <%= link_to '<i class="fi-widget"></i> Site Settings'.html_safe, settings_path %>
</div>
<div>
  <%= link_to '<i class="fi-archive"></i> Backup Site'.html_safe, backup_path %>
</div>
<div>
  <%= link_to '<i class="fi-upload-cloud"></i> Restore Site'.html_safe, restore_path %>
</div>
<div>
  <%= link_to '<i class="fi-lock"></i> Log out'.html_safe, signout_path, class:"right" %>
</div>

app/views/layouts/_bottom_nav.html.erb
<div class="bottom-nav-wrapper">
  <div class="bottom-nav">
    <%= link_to "", "#", 
      title:"Back to top", 
      class:"btt-logo" 
    %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="page-footer" class="row collapse">
  <% if !params[:id].nil? %>
    <% if !@prev_page.nil? || !@next_page.nil? %>
      <div class="large-4 small-12 columns text-center">
        <span id="prev-page">
          <% if !@prev_page.nil? %>
          <%= link_to "&#9664;".html_safe, @prev_page %>
          <% end %>
        </span>
        <% if params[:id] =~ /[0-9]+/ %>
          <span id="page-number">
            <%= params[:id] %>
          </span>
        <% end %>
        <span id="next-page">
          <% if !@next_page.nil? %>
            <%= link_to "&#9654;".html_safe, @next_page %>
          <% end %>
        </span>
      </div>
    <% end %>
    <div class="large-4 small-5 columns">
      <% if @post_type %>
      <%= link_to @post_type.name.titlecase, "/#{@post_type.name.gsub(/ /,"_")}" %>
      <% else %>
      <%= link_to params[:controller].titlecase, "/#{params[:controller]}" %>
      <% end %>
    </div>
    <% if !settings.nil? %>
      <div class="large-4 small-7 columns text-right">
        <%= settings.copy_notice.html_safe %>
      </div>
    <% end %>
  <% else %>
    <% if !settings.nil? %>
      <div class="small-5 columns">
        <a href="#">Home</a>
      </div>
      <div class="small-7 columns text-right">
        <%= settings.copy_notice.html_safe %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<% if !settings.nil? %>
		<nav id="header" class="row">
      <div class="columns large-11 large-centered">
        <% if false %>
          <a id="logo" class="image-logo" href="/"><%= settings.title %></a>
            <% link_to settings.title,
              root_path, 
              id:"logo", 
              class:"image-logo"
            %>
        <% else %>
          <div class="large-7 columns small-text-center">	
            <h1 id="logo" class="">
              <%= link_to settings.title, root_path %> 
            </h1>
          </div>
          <div class="large-5 columns right text-right small-text-center">
            <%= user_name %><br/>
            <div class="header-date">
              <% if @post && !@post.published_at.nil? %>
                <%= @post.published_at.strftime("%B %e, %Y") %>
              <% elsif @photo && !@photo.created_at.nil? %>
                <%= @photo.created_at.strftime("%B %e, %Y") %>
              <% else %>
                <%= Time.zone.now.strftime("%B %e, %Y") %>
              <% end %>
            </div>
          </div>
          <div class="columns">
            <%= render 'layouts/nav_bar' %>
          </div>
        <% end %>
      </div>
		</nav>
<% end %>

app/views/layouts/_nav_bar.html.erb
<div id="nav" class="row collapse text-center">
  <% if @categories.count > 0 && @categories.first.name == "Home" %>
    <% @categories = @categories.drop(1) %>
  <% end %>
  <% if @categories.length > 0 %>
    <% column_width = (100.0/@categories.length).round(3) %>
    <div id="main-menu-toggle" class="columns show-for-small">
      <a href="javascript:void(0)" class="menu-toggle" data-menu-id="main-menu">Categories</a>
    </div>
    <div class="show-for-small columns">
      <div id="main-menu" class="dropdown-menu show-for-small collapse clearout">
        <% @categories.each do |cat| %>
          <% unless cat.id == 1 %>
            <div class="columns">
              <%= link_to cat.name, "/#{cat.name.downcase.gsub(/ /,"_")}" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="hide-for-small">
      <% @categories.each do |cat| %>
        <% unless cat.id == 1 %>
          <div class="columns" style="width:<%= column_width %>%;">
            <%= link_to cat.name, "/#{cat.name.downcase.gsub(/ /,"_")}" %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <%= link_to "Create Post Type", new_post_type_path %>
  <% end %>
</div>

app/views/layouts/_post_menu.html.erb
<% if !["new","edit"].include?(params[:action]) %>
  <div class="columns large-2 left">
    <%= link_to '<i class="fi-plus"></i> New Post'.html_safe, new_post_path %>
  </div>
<% end %>

<% if @photo && params[:action] != "new" %>
  <div class="columns large-2 left">
    <%= link_to '<i class="fi-trash"></i> Delete Photo'.html_safe, 
      @photo, 
      method: :delete,
      confirm:"Are you sure?"
    %>
  </div>
<% elsif @post && params[:controller] != "photos" && ["show","index", "home"].include?(params[:action]) %>

  <div class="columns large-2 left">
    <%= link_to '<i class="fi-page-edit"></i> Edit Post'.html_safe, 
      edit_post_path(@post),
      id: "edit_link"
    %>
  </div>

  <div class="columns large-2 left">
    <%= link_to '<i class="fi-photo"></i> Add Photo'.html_safe, "/posts/#{@post.id}/photos/new" %>
  </div>

  <% if @post.id != 1 %>
    <% if @post.published_at.nil? %>
      <div class="columns large-2 left">
        <%= link_to '<i class="fi-check"></i> Publish'.html_safe, 
          "/posts/#{@post.id}/publish" %>
      </div>
    <% else %>
      <div class="columns large-2 left">
        <%= link_to '<i class="fi-x"></i> Unpublish'.html_safe, 
          "/posts/#{@post.id}/unpublish",
          confirm:"Unpublish post?" %>
      </div>
    <% end %>

    <div class="columns large-2 left">
      <%= link_to '<i class="fi-trash"></i> Delete Post'.html_safe, 
        @post,
        method: :delete,
        confirm:"Delete #{@post_type.name}?"
      %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_slider_controls.html.erb
<div id="slider-controls">
  <% if @post_type && @post_type.shifty_type && !["new","edit"].include?(params[:action]) %>
    <%= link_to "javascript:void(0)", id:"slider-prev", data:{target_id:0}, title:"Previous" do %>
      <div class="top-group">
        <span class="hide-for-small">< Prev</span>
        <span class="show-for-small"><</span>
      </div>
      <div class="bottom-group">
        < Previous
      </div>
      
    <% end %>
    <%= link_to "javascript:void(0)", id:"slider-next", data:{target_id:0},title:"Next" do %>
      <div class="top-group">
        <span class="hide-for-small">Next ></span>
        <span class="show-for-small">></span>
      </div>
      <div class="bottom-group">
        Next >
      </div>
    <% end %>
  <% elsif @photos && params[:controller] == "photos" %>
    <%= link_to "", "javascript:void(0)", id:"slider-prev", class:"photo-control", data:{target_id:0}, title:"Previous" %>
    <%= link_to "", "javascript:void(0)", id:"slider-next", class:"photo-control", data:{target_id:0}, title:"Next" %>
  <% end %>
</div>

app/views/layouts/_top_bar.html.erb
<div class="contain-to-grid">
  <nav class="top-bar">
    <section class="top-bar-section row">
      <div class="top-bar-controls">
        <div id="post-menu-toggle" class="columns small-6 show-for-small">
          <a href="javascript:void(0)" class="menu-toggle" data-menu-id="post-menu">
            <i class="fi-page-multiple"></i> Posts
          </a>
        </div>
        <div id="account-menu-toggle" class="columns small-6 large-2 right text-right">
          <a href="javascript:void(0)" class="menu-toggle" data-menu-id="account-menu">
            <i class="fi-results-demographics"></i> Account
          </a>
        </div>
      </div>

      <div class="columns large-10 hide-for-small text-center">
        <div class="large-2 columns text-center">
          <a href="javascript:void(0)" class="menu-toggle" data-menu-id="posts-sub-menu">
            <i class="fi-book"></i> All Posts
          </a>
        </div>

        <%= render 'layouts/post_menu' %>
      </div>

      <div class="columns show-for-small">
        <div id="post-menu" class="collapse text-center dropdown-menu shadow">
          <%= render 'layouts/post_menu' %>
        </div>
      </div>

      <div class="large-2 columns z-100">
        <div id="posts-sub-menu" class="collapse text-center dropdown-menu shadow">
          <div class="columns">
            <%= link_to '<i class="fi-list-bullet"></i> Post List'.html_safe, posts_path %>
          </div>

          <div class="columns no-padding left">
            <%= link_to '<i class="fi-results"></i> Post Types'.html_safe, post_types_path %>
          </div>
        </div>
      </div>

      <div class="columns large-2 right">
        <div id="account-menu" class="collapse text-center dropdown-menu shadow">
          <%= render 'layouts/account_menu' %>
        </div>
      </div>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>
    <% if false %>
      <link rel="shortcut icon" href="/assets/favicon.ico" type="image/vnd.microsoft.icon">
    <% end %>

    <%= stylesheet_link_tag    "application" %>
    <% if settings && !settings.font_style.nil? & !settings.font_link.nil? %>
      <%= settings.font_link.html_safe %>
      <style type="text/css">
        body,
        body *{
          <%= settings.font_style.html_safe %>
        }
      </style>
    <% end %>

    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="main-wrapper">
      <% if signed_in? %>
        <%= render 'layouts/top_bar' %>
      <% end %>
      <div id="main">
        <div id="greyout" style="display:none;"></div>
        <div id="clearout" style="display:none;"></div>
        <div id="main-content" class="row">
          <%= render 'layouts/header' %>
          <div id="body" class="row" style="position:relative;">
            <div class="columns large-11 large-centered">
              <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, class:"#{name} text-center flash" %>
              <% end %>

              <%= yield %>
              <%= render 'layouts/slider_controls' %>
              <%= render 'layouts/footer' %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <%= javascript_include_tag "application" %>
    <% if signed_in? %>
      <%= javascript_include_tag "admin" %>
    <% end %>
  </body>
</html>